name: Build wxPython
on:
  push:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:
  release:
    types: [published]
jobs:
  build:
    name: Build wxPython
    runs-on: macos-15
    if: github.repository_owner == 'hackdoc'
    permissions:
      contents: write
    env:
      # GitHub Information
      branch: ${{ github.ref }}
      commiturl: ${{ github.event.head_commit.url }}${{ github.event.release.html_url }}
      commitdate: ${{ github.event.head_commit.timestamp }}${{ github.event.release.published_at }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: |
          rm -rf Univ*
          rm -rf *pay*.dmg
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install -r requirements.txt
          aria2c -x 16 "https://github.com/hackdoc/PatcherSupportPkg/releases/download/push-8f0fc7d8311f13b55a05287db5e873d1a19fb5a8/Universal-Binaries.dmg"
      
      - name: Force Universal2 charset for Python
        run: |
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip uninstall -y charset_normalizer
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip download --platform macosx_10_9_universal2 --only-binary=:all: charset-normalizer
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 -m pip install charset_normalizer-*-macosx_10_9_universal2.whl

      - name: Prepare Assets (--prepare-assets)
      
        run: >
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 Build-Project.command
          --run-as-individual-steps
          --prepare-assets
      
      - name: Prepare Application (--prepare-application)
        run: >
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 Build-Project.command
          --git-branch "${{ env.branch }}" --git-commit-url "${{ env.commiturl }}" --git-commit-date "${{ env.commitdate }}"
          --reset-pyinstaller-cache
          --run-as-individual-steps
          --prepare-application

      - name: Prepare Package (--prepare-package)
        run: >
          /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 Build-Project.command
          --prepare-package
      - name: Delete previous pre-release
        if: github.event_name == 'push'
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 0
          delete_prerelease_only: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pre-Release on Push
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          #tag_name: push-${{ github.sha }}
          tag_name: 2.5.2
          name: 2.5.2
          body: ${{ github.event.head_commit.message }}
          prerelease: false
          files: |
            ./dist/AutoPkg-Assets.pkg
            ./dist/OCLP-R.pkg
            ./dist/OCLP-R-Uninstaller.pkg

      - name: Upload AutoPkg Package to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/AutoPkg-Assets.pkg
          tag: ${{ github.ref }}
          file_glob: true

      - name: Upload Installation Package to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/OCLP-R.pkg
          tag: ${{ github.ref }}
          file_glob: true

      - name: Upload Uninstaller Package to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/OCLP-R-Uninstaller.pkg
          tag: ${{ github.ref }}
          file_glob: true 
